version: "3.9"

services:
  social_m_api:
    image: postgres:16.9-bookworm
    container_name: social_m_api
    restart: always
    env_file:
      - .env
    ports: 
      - "5438:5432"
    volumes:
      - db_d:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-intidb.data

name: social_db

volumes:
  db_d:
